### PR TITLE
Polish looks and feel of archetype and add new main entity: Bookings

### PR DESCRIPTION
**Pull request by ulumulu1510**
This change is meant to make the archetype presentable in articles where we would show the strengths of Scout in combination with Jooq. For this, a new main entity has been created (Booking) and all Forms, Services and DataTables have been added. The Jooq setup has been slightly modified to suit the new entity.

The Document entity has been integrated as a sub-entity for Booking.

Various small changes have been made to facilitate better handling of archetype.

### CODE REVIEW

**Comment by padyx** [comment]
Hi there! Thank you for your contribution!
Since this is a rather big change, I've added @flwidmer as a reviewer.
He should comment here or contact you soon.

**Comment by flwidmer** [comment]
Thank you for the contribution, it runs fine and the archetype is properly synchronized. 

I don't understand the reasoning behind the DocumentsTable in the booking form. The documents are not stored per-booking. Each booking shows the same document. Is this intentional?

**Comment by flwidmer** [comment]
you may want to use `table.setValueSet(true);` in `DocumentService.getDocumentTableData` to trigger a reload after a document is deleted.

**Comment by ulumulu1510** [comment]
I now have addressed this issue and made a new commit.

**Comment by flwidmer** [comment]
Looks good now. Sorry for the delay.

**Pull request merged**
